[workspace]
authors = ["Pedro Augusto Sousa Gon√ßalves <pedro.asg@aluno.ufop.edu.br>"]
channels = ["conda-forge"]
name = "XAI_FSL"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
jupyter = "jupyter lab"

[dependencies]
python = ">=3.12,<3.13"
jupyterlab = ">=4.5.3,<5"
ipykernel = ">=7.1.0,<8"
pandas = ">=3.0.0,<4"
matplotlib = ">=3.10.8,<4"
pytorch = ">=2.10.0,<3"
torchvision = ">=0.25.0,<0.26"
numpy = ">=2.3.5,<3"
seaborn = ">=0.13.2,<0.14"
scikit-learn = ">=1.8.0,<2"
tqdm = ">=4.67.2,<5"
pillow = ">=12.1.0,<13"
opencv = ">=4.13.0,<5"
timm = ">=1.0.24,<2"
grad-cam = ">=1.5.5,<2"

[activation]
env = { PYTHONPATH = ".:$PYTHONPATH" }
